version: '3'
services:
  nginx:
    build: ./docker/nginx/
    container_name: next-ts-sample-app_nginx
    ports:
      - "80:80"
  express:
    build:
      context: ./
      dockerfile: ./docker/express/Dockerfile
    container_name: next-ts-sample-app_express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "53000:3000"
  postgres:
    build: ./docker/postgres/
    container_name: next-ts-sample-app_postgres
    ports:
      - "55432:5432"
    environment:
      # TODO: envファイルに外出ししたほうがいいかも
      POSTGRES_PASSWORD: postgres