version: '3'
services:
  nginx:
    build: ./docker/nginx/
    container_name: nginx
    ports:
      - "80:80"
  express:
    build:
      context: ./
      dockerfile: ./docker/express/Dockerfile
    container_name: express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
