version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
      args:
        EXPRESS_DOCKER_HOSTNAME: ${EXPRESS_DOCKER_HOSTNAME}
    container_name: next-ts-sample-app_nginx
    ports:
      - "80:80"
  express:
    build:
      context: ./
      dockerfile: ./docker/express/Dockerfile
    container_name: next-ts-sample-app_express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
  # MEMO: Amazon RDS/Auroraを利用する場合はコメントアウトし.envの接続先を変更
  postgres:
    build: ./docker/postgres/
    container_name: next-ts-sample-app_postgres
    ports:
      - "55432:5432"
    environment:
      # TODO: envファイルに外出ししたほうがいいかも
      POSTGRES_PASSWORD: postgres
  kotlin-backend:
    image: next-ts-sample-app_kotlin-backend
    container_name: next-ts-sample-kotlin-backend
    ports:
      - "8080:8080"
    environment:
      # Spring Bootで必要となる.envファイルのプロパティキーを記載
      EXPRESS_DOCKER_HOSTNAME: ${EXPRESS_DOCKER_HOSTNAME}
      POSTGRES_DOCKER_HOSTNAME: ${POSTGRES_DOCKER_HOSTNAME}
      APP_DBNAME: ${APP_DBNAME}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      BACKEND_DOCKER_HOSTNAME: ${BACKEND_DOCKER_HOSTNAME}
      BACKEND_HOSTNAME_AND_PORT: ${BACKEND_HOSTNAME_AND_PORT}
      FRONTEND_HOSTNAME_AND_PORT: ${FRONTEND_HOSTNAME_AND_PORT}