version: '3.3'
services:
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
      args:
        EXPRESS_DOCKER_HOSTNAME: ${EXPRESS_DOCKER_HOSTNAME}
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_nginx${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-app_nginx
    ports:
      - "80:80"
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-secret: "ecr-secret"
  express:
    build:
      context: ./
      dockerfile: ./docker/express/Dockerfile
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_express${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-app_express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
    labels:
      kompose.image-pull-secret: "ecr-secret"
  # MEMO: Amazon RDS/Auroraを利用する場合はコメントアウトし.envの接続先を変更
  postgres:
    build: ./docker/postgres/
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_postgres${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-app_postgres
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    environment:
      # TODO: envファイルに外出ししたほうがいいかも
      POSTGRES_PASSWORD: postgres
    labels:
      kompose.image-pull-secret: "ecr-secret"
  kotlin-backend:
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_kotlin-backend${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-kotlin-backend
    ports:
      - "8080:8080"
    environment:
      # Spring Bootで必要となる.envファイルのプロパティキーを記載
      EXPRESS_DOCKER_HOSTNAME: ${EXPRESS_DOCKER_HOSTNAME}
      POSTGRES_DOCKER_HOSTNAME: ${POSTGRES_DOCKER_HOSTNAME}
      APP_DBNAME: ${APP_DBNAME}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      BACKEND_DOCKER_HOSTNAME: ${BACKEND_DOCKER_HOSTNAME}
      BACKEND_HOSTNAME_AND_PORT: ${BACKEND_HOSTNAME_AND_PORT}
      FRONTEND_HOSTNAME_AND_PORT: ${FRONTEND_HOSTNAME_AND_PORT}
    labels:
      kompose.image-pull-secret: "ecr-secret"