version: '3'
services:
  nginx:
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_nginx${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-app_nginx
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: next-ts-sample-app-awslogs-group
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web
  express:
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_express${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-app_express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: next-ts-sample-app-awslogs-group
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: frontend
# MEMO: Fargateデプロイ時はPostgreSQLコンテナはデプロイしない。
#  postgres:
#    image: ${DOCKER_REGISTRY}/next-ts-sample-app_postgres${DOCKER_REPOSITORY_SUFFIX}
#    container_name: next-ts-sample-app_postgres
#    ports:
#      # エラーの回避のため、Dockerホスト側のポートはDockerコンテナ側と同じにしている。
#      # ※ローカル環境は5432を使っていることが多いため55432にずらしている。
#      # ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.
#      - "55432:55432"
#    environment:
#      # TODO: envファイルに外出ししたほうがいいかも
#      POSTGRES_PASSWORD: postgres
#    logging:
#      driver: awslogs
#      options: 
#        awslogs-group: next-ts-sample-app-awslogs-group
#        awslogs-region: ap-northeast-1
#        awslogs-stream-prefix: db

  kotlin-backend:
    image: ${DOCKER_REGISTRY}/next-ts-sample-app_kotlin-backend${DOCKER_REPOSITORY_SUFFIX}
    container_name: next-ts-sample-kotlin-backend
    expose: 
      - "8080"
    environment:
      # Spring Bootで必要となる.envファイルのプロパティキーを記載
      # TODO: コンテナビルド時は必要だけどECSデプロイ時はいらないものがありそう。要確認
      AWS_REGION: ${AWS_REGION}
      USER_POOL_ID: ${USER_POOL_ID}
      EXPRESS_HOSTNAME: ${EXPRESS_HOSTNAME}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      APP_DBNAME: ${APP_DBNAME}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      BACKEND_HOSTNAME: ${BACKEND_HOSTNAME}
      BACKEND_HOSTNAME_AND_PORT: ${BACKEND_HOSTNAME_AND_PORT}
      FRONTEND_HOSTNAME_AND_PORT: ${FRONTEND_HOSTNAME_AND_PORT}
    logging:
      driver: awslogs
      options: 
        awslogs-group: next-ts-sample-app-awslogs-group
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: backend

# TODO: portsのexpose化について未反映