version: '3'
services:
  nginx:
    image: 629540162457.dkr.ecr.ap-northeast-1.amazonaws.com/next-ts-sample-app_nginx
    container_name: nginx
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: next-ts-sample-app-awslogs-group
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: web
  express:
    image: 629540162457.dkr.ecr.ap-northeast-1.amazonaws.com/next-ts-sample-app_express
    container_name: express
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: next-ts-sample-app-awslogs-group
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: frontend